#========================== Filebeat autodiscover ==========================
# Autodiscover allows you to detect changes in the system and spawn new modules or inputs as they happen.
filebeat.autodiscover:
# Autodiscover docker containers and parse logs
  providers:
    - type: docker
      templates:
        - condition:
            regexp:
              docker.container.name: ".*(php|ruby|nodejs|mysql|nginx|redis|registry|rdbcbackup|web|worker|app|curator).*"
            # not:
            #   regexp:
            #     docker.container.name: ".*(elasticsearch|kibana|logstash|filebeat|metricbeat).*"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
              multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
              multiline.match: after
              processors:
                - add_docker_metadata: ~
                - add_locale: ~

#========================== Logstash output ==========================
output.logstash:
  hosts: [ "${LOGSTASH_HOST}:${LOGSTASH_BEATS_PORT}" ]

#========================== Setup ILM ==========================
setup.ilm.enabled: false

#========================== Elasticsearch template setting ==========================
setup.template.settings:
  name: "filebeat"
  pattern: "filebeat-*"
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression

#========================== Dashboards ==========================
setup.dashboards:
  enabled: true
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
