#========================== Modules ==========================
metricbeat.modules:
  #------------------------------- System Module -------------------------------
  - module: system
    metricsets:
      - cpu               # CPU usage
      - load              # CPU load averages
      - memory            # Memory usage
      - network           # Network IO
      - process           # Per process metrics
      - process_summary   # Process summary
      - socket_summary    # Socket summary
      - core              # Per CPU core usage
      - diskio            # Disk IO
      - socket            # Sockets and connection info (Linux)
      - network_summary   # Network IO summary (Linux)
      #- raid             # Raid
      #- service          # systemd service information (Linux)
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    period: 10s
    cpu.metrics:  ["percentages"]
    core.metrics: ["percentages"]
  - module: system
    period: 1m
    metricsets:
      - filesystem        # File system usage for each mountpoint
      - fsstat            # File system summary metrics
    processors:
    - drop_event.when.regexp:
        system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  - module: system
    period: 15m
    metricsets:
      - uptime            # System Uptime
  #------------------------------- Docker Module -------------------------------
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      - image
      - memory
      - network
    hosts: [ "unix:///var/run/docker.sock" ]
    period: 10s

#========================== Processors ==========================
processors:
- add_docker_metadata: ~
- add_cloud_metadata: ~
- add_locale: ~

#========================== Elasticsearch output ==========================
output.elasticsearch:
  hosts: ["${ELASTIC_HOST}:${ELASTIC_PORT}"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#========================== Setup ILM ==========================
setup.ilm.enabled: false

#========================== Elasticsearch template setting ==========================
setup.template:
  name: "metricbeat"
  pattern: "metricbeat-*"
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0     # Fix cluster health is yellow when cluster have only one node
    index.codec: best_compression

#========================== Dashboards ==========================
setup.dashboards:
  enabled: true
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
