actions:
  1:
    action: delete_indices
    description: >-
       Delete old indices in Elasticsearch logs (based on index name).
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: ${CURATOR_UNIT:days}
      unit_count: ${CURATOR_UNIT_COUNT:3}
      exclude: